### ISSUE TITLE
降低使用难度

### ISSUE THREAD

**Issue by UnspokenSpell** [Xposed-Modules-Repo/com.zhizi42.diymiuicard#1]
# 软件内的使用说明难以理解

## 句子太长

建议使用清晰易懂的表达方式，比如按点分段，合理断句。如果能配图会更好。

## 对象指代不明

![IMG_20230827_120323.jpg](https://github.com/Xposed-Modules-Repo/com.zhizi42.diymiuicard/assets/73733485/cf0e9e9a-40be-43ad-aae0-cfff87593ad5)

虽然想一想能明白，但不是马上。

**Comment by zhizi42** [comment]
作者语文不及格的 别骂了别骂了在改了 配图太麻烦了懒得写（
